sudo: false
dist: trusty

language: node_js
node_js:
  - "6"

branches:
  except:
  - /PROJ.*/

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
- pip install --user awscli

cache:
  pip: true
  directories:
    - node_modules
    - $HOME/api-server/node_modules

before_script:
  - bash setup-server.sh
  - npm run update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
